spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tekgroup
    username: root
    password: root
    


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    
    hibernate:
      ddl-auto: create
      
server:
  port: 8081
      
logging:
  file: /tmp/logs/myapplication.log



  

  
    
